system:
  admin-email: admin@oicq.com
  admin-password: adminadmin
  http-port: 8899
  https-port: 443
  db-type: sqlite
mysql:
  address: mysql.sqlpub.com
  port: 3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: imdemo
  username: imdemo
  password: 4cac6c1dbc54ff05
  max-idle-conns: 10
  max-open-conns: 100
sqlite:
  path: ./air.db