mysql:
  path:
  port: 3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: airgo
  username: airgo
  password:
  max-idle-conns: 10
  max-open-conns: 100
system:
  admin-email: admin@oicq.com
  admin-password: adminadmin
  http-port: 8899
  https-port: 443
  db-type: sqlite
sqlite:
  path: ./air.db